[package]
name = "mushroom-mc"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
env_logger = "0.11.8"
lazy_static = "1.5.0"
log = "0.4.28"
ron = "0.11.0"
tokio = {version = "1.48.0", features = ["full"]}
